### ISSUE TITLE
(question) How do multiple deeds in one map area work?

### ISSUE THREAD

**Issue by AbsorbingSafe11** [Ellpeck/CraftableDeeds#1]
(I would have left question on main page, but comments were disabled)
(sorry if wrong way to ask, fee free to delete if I was improper)
(I am unable to test myself since I don't have a second person or server to test with)

When playing multiplayer anyone who gains a deed would be able to claim an area, but what would happen to the user of a second deed in an already claimed area? (also are OPs and Admins effected by the deed?)

(also good job on the mod, it is one of the best area claiming mods I have seen)

**Comment by Ellpeck** [comment]
Re-claiming existing areas doesn't work. People with a permission level of at least 2 (that's the same as is required for using commnd blocks and the /day command) are uninhibited by claims.
