### ISSUE TITLE
[Qustion]

### ISSUE THREAD

**Issue by Taknax** [Ellpeck/CraftableDeeds#10]
This is a server utility in craftable survival style. This is really what i need for my mpdpack.
Can many other modpacker and i hope we get forge 1.12.2 version?

**Comment by Ellpeck** [comment]
This was a commission, so I don't accept suggestions for it. I'm sorry for the inconvenience.

**Comment by Taknax** [comment]
You dont need sry :)
is their a someone i can ask about. My english is not so good, so i didnt understand what you exactly mean by commision. I dont think the translator translated correctly. I am sry for the bothering.
