### ISSUE TITLE
[Question] do OPed players bypass the claim system entirely?

### ISSUE THREAD

**Issue by Wedge1453** [Ellpeck/CraftableDeeds#15]
I was helping a fellow server player set up protection for his base, and to test I tried doing stuff in his claim, and was succesful, is it because I have OP persmissions on the server?

**Comment by Ellpeck** [comment]
People that have the permission level specified in the config bypass the claim system. It defaults to 2, which is the same permission level required for the `tp` command. By default, an OP player has permission level 4.
