### ISSUE TITLE
[Suggestion] Make config for custom chunks claimed

### ISSUE THREAD

**Issue by dreckz** [Ellpeck/CraftableDeeds#18]
If possible see if making a config to modify the chunk radius claim.

This would be great for servers where they have chunk claims through 1 method but need either a lesser/stronger version to make things interesting.

Personally I wanted to do this on my server where I have Minecolonies where players can create permissions for their colony but if they need extra claims, they can add Craftable Deeds to make expansions to claims, but 8x8 is too much, was thinking of doing 3x3 chunks claims.

If possible also making different deeds that claim different amount of chunks each

**Comment by Ellpeck** [comment]
Sadly, this isn't easily possible.

As this mod was a commission, this is too complex of a feature to add.
