### ISSUE TITLE
Was wondering if you were open to suggestions?

### ISSUE THREAD

**Issue by Stuicide** [Ellpeck/CraftableDeeds#3]
This is SO close to something I have wanted for a long time. Was wondering if you were open to some suggestions to add to this mod.

Like:

Integrated highlights to claimed lands on a map
Sub-deeds. Deeds created on a Claimed plot that is a smaller portion of their claimed land, that can be given to another player (or sold) Delegating building rights to specific regions within a claimed plot of land. These deeds will have the Owner (original owner) and a Tenent (someone who has rights to a specific portion of a deed plot)
A Deed Portfolio, where one can store all their deeds in a book-like item.
(have yet to test the mod out just yet but if this is not already integrated) ability to name the plotted land, as in a City/town name. (to also be shown in the highlighted areas on a map)

Would have posted this in curse forge, but comments did not seem to be enabled.

Either way, keep up the great work!

**Comment by Ellpeck** [comment]
I'm sorry, but this mod was a commission, meaning I'm not open to suggestions.
