### ISSUE TITLE
Getting in contact regarding suggestions

### ISSUE THREAD

**Issue by celsiusqc** [Ellpeck/CraftableDeeds#6]
hey!
I would like to get into contact with you because I have some ideas I think you would like that could be added to your mod. They are not hard ideas to implement and could add a lot to servers. It would be the first of its kind.
My discord is celsius.qc#5168  if you would like to contact me or through github!
Thanks

**Comment by Ellpeck** [comment]
This was a commission, so I don't accept suggestions for it. I'm sorry for the inconvenience.
