### ISSUE TITLE
questions.

### ISSUE THREAD

**Issue by legendaryA1** [Ellpeck/CraftableDeeds#7]
I was wondering if you would be able to add someone like a claim detection so you could just right click and it would tell you if it was claimed or if you entered or exited a protection. and if you could add something into the config to edit the size of the claim or more deeds of different sizes. as a modpack creator this would be very helpful.

**Comment by Ellpeck** [comment]
This was a commission, so I don't accept suggestions for it. I'm sorry for the inconvenience.
