### ISSUE TITLE
CLAIMING BUG

### ISSUE THREAD

**Issue by celsiusqc** [Ellpeck/CraftableDeeds#8]
Hi, Please add support for deployers from create mod to work in claimed chunks with a deed.
Thank-you
(this is the same for other mods that place blocks such as Industrial Forgoing and others. FTBChunks does it by "allying" the mod so the deployer can work. Is there a way to do the same with your mod? This would be VERY Useful. 
Thank-you

**Comment by Ellpeck** [comment]
Support for this will be added in the upcoming update.
