### ISSUE TITLE
Craftable Deeds 2.0 Breaking blocks without whitelist crashes client

### ISSUE THREAD

**Issue by mitchthetroll** [Ellpeck/CraftableDeeds#9]
Hello, on my server a player who wasn't whitelisted tried to interact with a waystone as well as break a block and it crashed their client both times. This was recreated with a second player too. Heres the crash log, thanks and great mod just need to iron out a few bugs 

here's the crash log
[crash-2021-03-14_03.20.35-client.txt](https://github.com/Ellpeck/CraftableDeeds/files/6313822/crash-2021-03-14_03.20.35-client.txt)

**Comment by mitchthetroll** [comment]
After a lot of testing, I believe this bug only happens when the owner of the Deed doesn't interact with their pedestals to allow/not allow people to interact with the land. So if a player just stumbles upon someone's territory and the owner never changed their settings they will crash when trying to break or open something

**Comment by Ellpeck** [comment]
That... crash report has absolutely nothing to do with Craftable Deeds. It doesn't even seem to be installed.

**Comment by mitchthetroll** [comment]
ah, maybe my friend sent me the wrong log... makes sense becasue thats from march 14th lol my bad

**Comment by mitchthetroll** [comment]
ill get the correct one soon

**Comment by mitchthetroll** [comment]
[crash-2021-04-14_16.23.03-client.txt](https://github.com/Ellpeck/CraftableDeeds/files/6314521/crash-2021-04-14_16.23.03-client.txt)
here we go
